Update migration_workflow.yml

diff --git a/.github/workflows/migration_workflow.yml b/.github/workflows/migration_workflow.yml
--- a/.github/workflows/migration_workflow.yml
+++ b/.github/workflows/migration_workflow.yml
@@ -15,17 +15,17 @@ jobs:
     - name: Set up PowerShell
       uses: actions/setup-python@v4
 
-#    - name: Validate PAT tokens
-#      run: |
-#        if [[ -z "${{ secrets.SOURCE_TOKEN }}" ]]; then
-#          echo "Source Token is missing!"
-#          exit 1
-#        fi
-#        if [[ -z "${{ secrets.TARGET_TOKEN }}" ]]; then
-#          echo "Target Token is missing!"
-#          exit 1
-#        fi
-#      shell: bash
+    - name: Validate PAT tokens
+      run: |
+        if [[ -z "${{ secrets.SOURCE_TOKEN }}" ]]; then
+          echo "Source Token is missing!"
+          exit 1
+        fi
+        if [[ -z "${{ secrets.TARGET_TOKEN }}" ]]; then
+          echo "Target Token is missing!"
+          exit 1
+        fi
+      shell: bash
 
     - name: Get Issue Body
       id: issue_body
